### PR TITLE
CommonHTML fixes for digits, Jeem, and Haa

### LINKED ISSUE #10: Too tall square root when numbers used
The number (8) inside the square root symbol should be lowered down a bit. Script: `\sqrt{8}` . The problem is not there when you have a variable inside the square root. It is only appears when for square roots of simple numeric number.

image

Another example with the problem: `\sqrt{456-123}`
But this one is good! : `\sqrt{456-123-x}`

Another example:
image

### PR DESCRIPTION
**Pull request by shadinaif**
In **CommonHTML** enviroment: this is to fix the render for some scripts related to numbers and letters with (tatweel جـ هـ):

### Test case 1
fix position for `\frac` operator
`\frac{1}{2}+\frac{A}{B}+\frac{C}{E}`
before:
selection_006

after:
selection_007

### Test case 2
fix over-line position for numbers
`\overline{A}\space\overline{B}\space\overline{0}\space\overline{1}\space\overline{2}`
before:
selection_008

after:
selection_009

### Test case 3:
fix over-line position for **Jeem** and **Haa**
`\overline{A}\overline{B}\overline{C}\overline{D}\overline{E}\overline{F}`
before:
selection_020

after:
selection_011

### Test case 4:
fix bar position for **Jeem** and **Haa**
`\bar{A}\bar{B}\bar{C}\bar{D}\bar{E}\bar{F}`
before:
selection_012

after:
selection_013

### Test case 5:
fix numbers position inside square root. Applied on **Jeem** and **Haa** too
`\sqrt{12345678c}`
before:
selection_014

 after:
selection_015

**Test Case 6** has been removed because it is not valid in Arabic. Users must use `\transn` to represent decimals. That will convert the *dot* to the Arabic decimal *comma* separator
Example: `\transn{1.234}\\\overline{\transn{1.234}}`
selection_022

### ~~Test case 6:~~
~~fix text alignment for decimal numbers when used with **\\\\**~~
~~`1.234\\\overline{1.234}`~~
~~before:~~
selection_021

Fixes #10

### CODE REVIEW

**Comment by shadinaif** [comment]
@OmarIthawi  This PR is ready for your review :)

**Comment by OmarEdraak** [comment]
@shadinaif Please bump up the version (like we did in bc9ff76ca144df9d0a7c5834f55bef717b240888) to `2.1.0`, to denote the major updates you've done.

I think all of the changes look good, but I need to double check on the Test Case 6 updates shortly.

**Comment by OmarIthawi** [comment]
@shadinaif Please bump up the version (like we did in bc9ff76ca144df9d0a7c5834f55bef717b240888) to `2.1.0`, to denote the major updates you've done.

I think all of the changes look good, but I need to double check on the Test Case 6 updates shortly.

**Comment by shadinaif** [comment]
Version bump is done @OmarIthawi .

Regarding Test Case 6, this is the fixing code https://github.com/OmarIthawi/arabic-mathjax/pull/16/commits/87049901840ed0c7294855651e10dc151a97ee8b#diff-0f0b9bfbcff9748d4ec0e7b8ebd1ebe0R43

**Comment by OmarIthawi** [comment]
> Version bump is done @OmarIthawi .
> 
> Regarding Test Case 6, this is the fixing code [8704990#diff-0f0b9bfbcff9748d4ec0e7b8ebd1ebe0R43](https://github.com/OmarIthawi/arabic-mathjax/commit/87049901840ed0c7294855651e10dc151a97ee8b#diff-0f0b9bfbcff9748d4ec0e7b8ebd1ebe0R43)

Thanks @shadinaif, I've copied it to a new issue (#17). Will take a look soon.

**Comment by shadinaif** [comment]
@OmarIthawi Thank you for opening the new issue https://github.com/OmarIthawi/arabic-mathjax/issues/17 . Indeed, the `\transn` should be retiring (carefully) :+1: 

I believe the PR is ready now for your final review

**Review by OmarIthawi — APPROVED** [review]
LGTM!

**Pull request merged**
